- name: CREATE STUDENT WEBPAGE
  template:
    src: ./templates/index.html.j2
    dest: "{{ playbook_dir }}/webpage/{{ ec2_name_prefix|lower }}-index.html"
  when: s3_state == 'present'

- name: CREATE S3 BUCKET
  s3_bucket:
    name: "{{ec2_name_prefix|lower}}.{{openshift_base_domain|lower}}"
    state: "{{ s3_state }}"
    region: "{{aws_region}}"
    force: yes

- name: ENABLE WEB HOSTING
  s3_website:
   name: "{{ec2_name_prefix|lower}}.{{openshift_base_domain|lower}}"
   state: "{{ s3_state }}"
   region: "{{aws_region}}"
   suffix: "{{ ec2_name_prefix|lower }}-index.html"
  register: s3_site
  when: s3_state == 'present'

- name: DNS FOR STUDENT WEBPAGE FOR US-EAST-1
  route53:
    state: "{{ s3_state }}"
    zone: "{{openshift_base_domain}}"
    record: "{{ec2_name_prefix|lower}}.{{openshift_base_domain}}"
    type: CNAME
    overwrite: yes
    value: "{{ec2_name_prefix|lower}}.{{openshift_base_domain}}.s3-website-{{aws_region}}.amazonaws.com"
  when:
    - aws_region == 'us-east-1'

- name: DNS FOR WEBPAGE
  route53:
    state: "{{ s3_state }}"
    zone: "{{openshift_base_domain}}"
    record: "{{ec2_name_prefix|lower}}.{{openshift_base_domain}}"
    type: CNAME
    overwrite: yes
    value: "{{ec2_name_prefix|lower}}.{{openshift_base_domain}}.s3-website.{{aws_region}}.amazonaws.com"
  when:
    - aws_region != 'us-east-1'

- name: PUT STUDENT WEBPAGE
  s3_sync:
    bucket: "{{ec2_name_prefix|lower}}.{{openshift_base_domain}}"
    region: "{{aws_region}}"
    file_root: "{{ playbook_dir }}/webpage"
    mime_map:
      .html: text/html
    permission: public-read
    include: "{{ ec2_name_prefix|lower }}-index.html"
  when: s3_state == 'present'
