---

- name: Copy script for caching CI/CD images across nodes
  copy:
    src: "../files/cache_docker_images.yml"
    dest: "/home/{{ ansible_user }}/cache_docker_images.yml"
    mode: 0644

- name: Copy script for DC Metro Map (DCMM) installation
  template:
    src: "../files/install-dcmm.sh"
    dest: "/home/{{ ansible_user }}/install-dcmm.sh"
    mode: 0775

- name: Provide details to check DCMM installation
  debug:
    msg: |
         Check file '/home/{{ ansible_user }}/install-dcmm.log' on '{{ openshift_public_hostname }}'
         To access ec2 instance 'ssh -i {{ ec2_key_file }} ec2-user@{{ openshift_public_hostname }}'

- name: Run DCMM installation script
  shell: ./install-dcmm.sh |& tee install-dcmm.log
  args:
   chdir: "/home/{{ ansible_user }}"
